-- MySQL Script generated by MySQL Workbench
-- Sat Jan 20 13:24:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `RoleId` INT NOT NULL,
  `RoleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `RoleId` INT NOT NULL DEFAULT '2',
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserId`),
  INDEX `fk_Users_Role1_idx` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Role1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `mydb`.`role` (`RoleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `CustId` INT NOT NULL AUTO_INCREMENT,
  `CustName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(10) NOT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `UserId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CustId`),
  INDEX `fk_Customer_Users_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Users`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`firm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firm` (
  `FirmId` INT NOT NULL AUTO_INCREMENT,
  `FirmName` VARCHAR(255) NOT NULL,
  `FirmAddress` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FirmId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `Firm_FirmId` INT NULL DEFAULT '1',
  `UserId` INT NOT NULL,
  `EmpId` INT NOT NULL AUTO_INCREMENT,
  `EmpName` VARCHAR(255) NOT NULL,
  `EmpType` ENUM('courier', 'office worker') NOT NULL,
  PRIMARY KEY (`EmpId`),
  INDEX `fk_Employees_Firm1_idx` (`Firm_FirmId` ASC) VISIBLE,
  INDEX `fk_Employees_Users1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Firm1`
    FOREIGN KEY (`Firm_FirmId`)
    REFERENCES `mydb`.`firm` (`FirmId`),
  CONSTRAINT `fk_Employees_Users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`users` (`UserId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offices` (
  `Firm_FirmId` INT NOT NULL,
  `OfficeId` INT NOT NULL AUTO_INCREMENT,
  `OfficeName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`OfficeId`),
  INDEX `fk_offices_Firm1_idx` (`Firm_FirmId` ASC) VISIBLE,
  CONSTRAINT `fk_offices_Firm1`
    FOREIGN KEY (`Firm_FirmId`)
    REFERENCES `mydb`.`firm` (`FirmId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statuses` (
  `StatusId` INT NOT NULL AUTO_INCREMENT,
  `StatusName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`StatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`parcels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parcels` (
  `ParcelsId` INT NOT NULL AUTO_INCREMENT,
  `SenderId` INT NOT NULL,
  `ReceiverId` INT NOT NULL,
  `OfficeOrAddress` INT NOT NULL,
  `SenderAddress` VARCHAR(255) NOT NULL,
  `ReceiverAddress` VARCHAR(255) NOT NULL,
  `Weight` DOUBLE NOT NULL,
  `Price` DOUBLE NOT NULL,
  `StatusId` INT NULL DEFAULT NULL,
  `EmpId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ParcelsId`),
  INDEX `fk_packages_clients1_idx` (`SenderId` ASC) VISIBLE,
  INDEX `fk_packages_clients2_idx` (`ReceiverId` ASC) VISIBLE,
  INDEX `fk_packages_statuses1_idx` (`StatusId` ASC) VISIBLE,
  INDEX `fk_packages_employees1_idx` (`EmpId` ASC) VISIBLE,
  CONSTRAINT `fk_packages_clients1`
    FOREIGN KEY (`SenderId`)
    REFERENCES `mydb`.`customer` (`CustId`),
  CONSTRAINT `fk_packages_clients2`
    FOREIGN KEY (`ReceiverId`)
    REFERENCES `mydb`.`customer` (`CustId`),
  CONSTRAINT `fk_packages_employees1`
    FOREIGN KEY (`EmpId`)
    REFERENCES `mydb`.`employees` (`EmpId`),
  CONSTRAINT `fk_packages_statuses1`
    FOREIGN KEY (`StatusId`)
    REFERENCES `mydb`.`statuses` (`StatusId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
